project:
  type: website
  output-dir: docs

website:
  title: "Brynjólfur Gauti Guðrúnar Jónsson"
  site-url: https://www.bggj.is
  description: Blogg um tölfræði og gögn
  favicon: favicon.ico
  repo-url: https://github.com/bgautijonsson/bgautijonsson.github.io
  twitter-card: 
    creator: "@bgautijonsson"
    card-style: summary_large_image
  navbar:
    background: "#08306b"
    foreground: "#ffffff"
    right:
      - href: pages/about.qmd
        text: Um mig
      - href: pages/radgjof.qmd
        text: Ráðgjöf
      - href: index.qmd
        text: Færslur
      - text: Verkefni
        menu:
            - text: Mælaborð Sveitarfélaga
              href: pages/sveitarfelog.qmd
            - text: Mælaborð COVID-19
              href: http://covid.rhi.hi.is/shiny/dashboard/
            - text: Spálíkan COVID-19
              href: pages/covid_spalikan.qmd
      - icon: github
        href: https://github.com/bgautijonsson
      - icon: twitter
        href: https://twitter.com/bgautijonsson
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css



