project:
  type: website

website:
  title: "bgautijonsson.github.io"
  navbar:
    background: "#08306b"
    foreground: "#ffffff"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



