project:
  type: website
  output-dir: docs

website:
  title: "Brynjólfur Gauti Guðrúnar Jónsson"
  site-url: "https://www.bggj.is"
  description: Blogg um tölfræði og gögn
  page-footer: 
    left: "Copyright 2022, Brynjólfur Gauti Guðrúnar Jónsson"
    right: 
        - icon: github
          href: https://github.com/bgautijonsson
        - icon: twitter
          href: https://twitter.com/bgautijonsson
    center:
        - text: Styrkja mig
          href: https://www.buymeacoffee.com/bggj
  favicon: favicon.ico
  repo-url: https://github.com/bgautijonsson/bgautijonsson.github.io
  google-analytics: "G-EGQ9KVCY2C"
  open-graph: true
  twitter-card: 
    creator: "@bggjonsson"
    card-style: summary_large_image
    site: "@bggjonsson"
  navbar:
    background: "#08306b"
    foreground: "#ffffff"
    right:
      - href: index.qmd
        text: Um mig
      - href: pages/radgjof.qmd
        text: Ráðgjöf
      - href: posts.qmd
        text: Færslur
      - text: Mælaborð
        menu:
            - text: Fjármál Sveitarfélaga
              href: sveitarfelog.qmd
            - text: COVID-19 (Uppfærslum hætt)
              href: http://covid.rhi.hi.is/shiny/dashboard/
            - text: Eignir, skuldir og tekjur
              href: skattagogn.qmd
      - text: Verkefni
        menu:
            - text: Spálíkan COVID-19
              href: pages/covid_spalikan.qmd
      - icon: github
        href: https://github.com/bgautijonsson
      - icon: twitter
        href: https://twitter.com/bggjonsson
      - icon: rss
        href: index.xml
format:
  html:
    theme: theme.scss
    css: styles.css



