project:
  type: website
  output-dir: docs

website:
  title: "Brynjólfur Gauti Guðrúnar Jónsson"
  site-url: https://www.bggj.is
  description: Blogg um tölfræði og gögn
  twitter-card: 
    creator: "@bgautijonsson"
  navbar:
    background: "#08306b"
    foreground: "#ffffff"
    right:
      - href: about.qmd
        text: Um mig
      - text: Verkefni
        menu:
            - text: Mælaborð Sveitarfélaga
              href: sveitarfelog.qmd
            - text: Mælaborð COVID-19
              href: http://covid.rhi.hi.is/shiny/dashboard/
            - text: Spálíkan COVID-19
              href: covid_spalikan.qmd
      - icon: github
        href: https://github.com/bgautijonsson
      - icon: twitter
        href: https://twitter.com/bgautijonsson
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css



