project:
  type: website
  output-dir: docs

website:
  title: "bgautijonsson.github.io"
  site-url: https://www.bgautijonsson.github.io
  description: Blogg um tölfræði og gögn
  twitter-card: 
    creator: "@bgautijonsson"
  navbar:
    background: "#08306b"
    foreground: "#ffffff"
    right:
      - href: about.qmd
        text: Um mig
      - icon: github
        href: https://github.com/bgautijonsson
      - icon: twitter
        href: https://twitter.com/bgautijonsson
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css



