---
title: "Fjármál stjórnmálaflokkanna"
author: 
    -   name: "Brynjólfur Gauti Guðrúnar Jónsson"
        url: "https://twitter.com/bgautijonsson"
        affiliation: "Tölfræði, Raunvísindadeild Háskóla Íslands"
        affiliation-url: "https://www.hi.is/tolfraedi_0"
date: "2022/08/13"
format: 
    html:
        code-fold: true
        toc: true
        toc-depth: 2
        toc-location: right
        toc-title: Efnisyfirlit
        page-layout: full
        smooth-scroll: true
        link-external-newwindow: true
execute: 
  echo: true
  warning: false
  cache: false
editor: source
draft: false
title-block-banner: true
categories:
    - stjórnmál
    - efnahagur
    - ársreikningar
    - R
    - íslenska

---


```{r}
#| include: false

library(cowplot)
library(tidyverse)
library(scales)
library(ggthemes)
library(kableExtra)
library(gganimate)
library(lubridate)
library(geomtextpath)
library(ggtext)
library(readxl)
library(janitor)
library(plotly)
library(config)
library(DBI)
library(visitalaneysluverds)
```

```{r}
usr <- config::get("postgres_user")
con <- dbConnect(RPostgres::Postgres(), 
                 dbname = usr$dbname, 
                 host = usr$host,
                 port = usr$port, 
                 user = usr$username, 
                 password = usr$password)
```


```{r}
d <- tbl(con, "arsreikningar_stjornmalaflokka") |> 
    collect() |> 
    mutate_all(~ ifelse(is.na(.), 0, .)) |> 
    inner_join(
        vnv() |> 
            group_by(ar = year(date)) |> 
            summarise(cpi = mean(cpi)) |> 
            mutate(cpi = cpi / cpi[ar == max(ar)]),
        by = "ar"
    )

xS <- "#e41a1c"
xV <- "#238b45"
xD <- "#377eb8"
xP <- "#984ea3"
xB <- "#b2df8a"
xBF <- "#cab2d6"
xC <- "#ff7f00"
xM <- "#08306b"
xFF <- "#fee391"
Annad <- "#e5d8bd"
```


# Framlög til stjórnmálaflokka

## Ríkissjóður

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = (framlog_rikis + framlog_althingi) / cpi) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xFF, xC, xM, xP, xB, xV, xS, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing framlaga ríkissjóðs á stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```


## Sveitarfélög

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = framlog_svf / cpi) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xFF, xC, xM, xP, xB, xV, xS, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing framlaga sveitarfélaga á stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```

## Fyrirtæki og lögaðilar

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = framlog_fyrirtaekja / cpi) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xFF, xC, xM, xP, xB, xV, xS, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing framlaga fyrirtækja/lögaðila á stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```

## Aðrar tekjur

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = adrar_tekjur / cpi) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xFF, xC, xM, xP, xB, xV, xS, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing annarra tekna stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```

## Heildartekjur

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = tekjur / cpi) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xFF, xC, xM, xP, xV, xB, xS, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing heildartekna stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```


## Einstaklingar

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = framlog_einstaklinga / cpi) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xFF, xC, xM, xP, xB, xV, xS, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing framlaga einstaklinga á stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```

# Eignir, skuldir og eigið fé

## Eignir

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = eignir / cpi) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xC, xFF, xM, xP, xV, xS, xB, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing eigna stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```

## Skuldir

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = skuldir / cpi) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xC, xFF, xM, xP, xV, xS, xB, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing skulda stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```

## Eigið fé

```{r}
#| fig-asp: 0.621
#| fig-width: 10
#| out-width: "100%"

plot_dat <- d |> 
    mutate(framlog = (eignir - skuldir) / cpi,
           framlog = ifelse(framlog < 0, 0, framlog)) |> 
    select(ar, flokkur, framlog) |> 
    mutate(flokkur = fct_reorder(flokkur, framlog, .fun = sum))


p <- plot_dat |> 
    ggplot(aes(ar, framlog)) +
    geom_col(aes(fill = flokkur), position = "fill", colour = "grey95", width = 1) +
    scale_x_continuous() +
    scale_y_continuous(labels = label_percent()) +
    scale_fill_manual(values = c(
        xC, xFF, xM, xP, xV, xS, xB, xD
    )) +
    coord_cartesian(expand = FALSE) +
    theme_half_open() +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Dreifing eigin fjár stjórnmálaflokka (2007 - 2020)")

ggplotly(
    p
)
```